package com.roboto;      // :) :) :)
import java.awt.Desktop;      // :) :) :)
import java.io.IOException;      // :) :) :)
import java.net.URI;      // :) :) :)
import java.net.URISyntaxException;      // :) :) :)
      // :) :) :)
public class Main {      // :) :) :)
      // :) :) :)
    public static void main(String[] args) {      // :) :) :)
        if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {      // :) :) :)
            try {      // :) :) :)
                Desktop.getDesktop().browse(new URI("https://www.youtube.com/watch?v=dQw4w9WgXcQ"));       // :) :) :)
            } catch (IOException e) {      // :) :) :)
                e.printStackTrace();      // :) :) :)
            } catch (URISyntaxException e) {      // :) :) :)
                e.printStackTrace();      // :) :) :)
            }      // :) :) :)
        }      // :) :) :)
    }      // :) :) :)
}      // :) :) :)